FROM openjdk

RUN mkdir /usr/local/app
COPY ./target/ta-webapp-bundled-1.0-SNAPSHOT.jar /usr/local/app/ta-webapp-bundled-1.0-SNAPSHOT.jar
COPY ./credentials.json /usr/local/app/credentials.json

EXPOSE 4567

ENV GOOGLE_APPLICATION_CREDENTIALS=/usr/local/app/credentials.json

WORKDIR /usr/local/app

ENTRYPOINT [ "java", "-cp", "ta-webapp-bundled-1.0-SNAPSHOT.jar", "com.zuhlke.ta.web.Application", "analytics-174711", "camp_exercise", "tweets" ]