apiVersion: v1
kind: Service
metadata:
  name: couchbase-service
spec:
  ports:
  - port: 8091
    name: "web-admin"
    protocol: TCP
  - port: 8092
    name: "api"
    protocol: TCP
  - port: 8093
    name: "query"
    protocol: TCP
  - port: 8094
    name: "search"
    protocol: TCP
  - port: 11210
    name: "smart-client"
    protocol: TCP
  - port: 11211
    name: "non-smart-client"
    protocol: TCP
  selector:
    app: couchbase